import { useEffect, useState } from 'react';
import { Check, Download, X } from 'lucide-react';
import { getApiErrorMessage } from '../../auth/api';
import { downloadPrivateFile } from '../../files/api';
import { reportsApi } from '../../reports/api';
import type { ReportRecord } from '../../reports/types';

export const ReviewReports = () => {
  const [items, setItems] = useState<ReportRecord[]>([]); const [selected, setSelected] = useState<ReportRecord | null>(null); const [feedback, setFeedback] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { try { setItems((await reportsApi.supervised({ limit: 100 })).items); } catch (e) { setError(getApiErrorMessage(e)); } };
  useEffect(() => { void load(); }, []);
  const review = async (status: 'APPROVED' | 'REJECTED') => { if (!selected) return; setBusy(true); try { await reportsApi.review(selected.id, { status, feedback: feedback || undefined }); setSelected(null); setFeedback(''); await load(); } catch (e) { setError(getApiErrorMessage(e)); } finally { setBusy(false); } };
  const download = async (fileId: string) => { try { await downloadPrivateFile(fileId); } catch (e) { setError(getApiErrorMessage(e)); } };
  return <div className="space-y-6"><div className="bg-white rounded-2xl p-6 border"><h2 className="text-xl font-bold">Duyệt báo cáo tuần</h2><p className="text-xs text-slate-500 mt-1">Báo cáo của sinh viên đang được bạn hướng dẫn.</p></div>{error && <p className="text-rose-700 bg-rose-50 p-3 rounded-xl">{error}</p>}<div className="space-y-3">{items.map((report) => <article key={report.id} className="bg-white rounded-2xl border p-5"><div className="flex justify-between"><div><h3 className="font-bold">{report.placement.student.fullName} · Tuần {report.week}</h3><p className="text-xs text-slate-500">{report.placement.student.studentCode} · {report.placement.company.companyName}</p></div><b className="text-xs">{report.status}</b></div><p className="mt-3 whitespace-pre-line text-sm">{report.content}</p>{report.file && <button onClick={() => void download(report.file!.id)} className="mt-3 text-blue-700 text-xs font-bold flex gap-1"><Download className="w-4" />{report.file.originalName}</button>}{report.status === 'SUBMITTED' && <button onClick={() => { setSelected(report); setFeedback(''); }} className="mt-4 block ml-auto bg-purple-600 text-white text-xs font-bold px-4 py-2 rounded-xl">Duyệt & nhận xét</button>}</article>)}</div>{selected && <div className="fixed inset-0 z-50 bg-slate-900/50 flex p-4 items-center justify-center"><div className="bg-white rounded-2xl p-6 max-w-md w-full"><button className="float-right" onClick={() => setSelected(null)}><X /></button><h3 className="font-bold">Tuần {selected.week} · {selected.placement.student.fullName}</h3><textarea rows={4} className="mt-4 w-full border rounded p-2" value={feedback} onChange={(e) => setFeedback(e.target.value)} placeholder="Nhận xét cho sinh viên" /><div className="grid grid-cols-2 gap-2 mt-3"><button disabled={busy} onClick={() => void review('APPROVED')} className="bg-emerald-600 text-white rounded-xl p-2 text-sm font-bold"><Check className="inline w-4" /> Duyệt</button><button disabled={busy} onClick={() => void review('REJECTED')} className="bg-rose-100 text-rose-800 rounded-xl p-2 text-sm font-bold">Yêu cầu sửa</button></div></div></div>}</div>;
};
