import React, { useEffect, useMemo, useState } from 'react';
import { Award, Save } from 'lucide-react';
import type { EvaluationRecord } from '../../evaluations/api';
import type { PlacementRecord } from '../../placements/types';

interface Props { placements: PlacementRecord[]; evaluations: EvaluationRecord[]; onSubmit: (input: { placementId: string; score: number; comment: string }) => Promise<void>; onUpdate: (id: string, input: { score: number; comment: string }) => Promise<void>; }

export function TeacherEvaluations({ placements, evaluations, onSubmit, onUpdate }: Props) {
  const evaluable = useMemo(() => placements.filter((p) => p.status === 'ACTIVE' || p.status === 'COMPLETED'), [placements]);
  const [placementId, setPlacementId] = useState(''); const [score, setScore] = useState(8); const [comment, setComment] = useState(''); const [saving, setSaving] = useState(false);
  const selectedId = placementId || evaluable[0]?.id || ''; const lecturerEvaluation = evaluations.find((item) => item.placementId === selectedId && item.type === 'LECTURER'); const companyEvaluations = evaluations.filter((item) => item.type === 'COMPANY');
  useEffect(() => { if (lecturerEvaluation) { setScore(lecturerEvaluation.score); setComment(lecturerEvaluation.comment ?? ''); } else { setScore(8); setComment(''); } }, [lecturerEvaluation?.id, selectedId]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!selectedId) return; setSaving(true); try { if (lecturerEvaluation) await onUpdate(lecturerEvaluation.id, { score, comment }); else await onSubmit({ placementId: selectedId, score, comment }); } finally { setSaving(false); } };
  return <div className="space-y-6"><div className="bg-white rounded-2xl p-6 border border-slate-200"><h2 className="text-xl font-bold">Tổng hợp đánh giá thực tập</h2><p className="text-xs text-slate-500 mt-1">Điểm giảng viên là một đánh giá độc lập, không ghi đè đánh giá doanh nghiệp.</p></div>{companyEvaluations.map((ev) => <div key={ev.id} className="bg-white rounded-2xl border p-5"><div className="flex justify-between gap-3"><div><h3 className="font-bold">{ev.placement.student.fullName}</h3><p className="text-xs text-slate-500">{ev.placement.company.companyName} · {ev.placement.internship.title}</p></div><span className="font-bold text-emerald-700"><Award className="inline w-4 h-4" /> {ev.score}/10</span></div><p className="mt-3 text-sm text-slate-600">{ev.comment || 'Không có nhận xét'}</p></div>)}{evaluable.length > 0 && <form onSubmit={submit} className="bg-white rounded-2xl border p-6 space-y-4"><h3 className="font-bold">{lecturerEvaluation ? 'Cập nhật đánh giá của giảng viên' : 'Thêm đánh giá của giảng viên'}</h3><select value={selectedId} onChange={(e) => setPlacementId(e.target.value)} className="w-full p-3 border rounded-xl">{evaluable.map((p) => <option key={p.id} value={p.id}>{p.student.fullName} — {p.internship.title}</option>)}</select><input required type="number" min="0" max="10" step="0.01" value={score} onChange={(e) => setScore(Number(e.target.value))} className="w-full p-3 border rounded-xl" /><textarea required rows={4} value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Nhận xét tổng kết" className="w-full p-3 border rounded-xl" /><button disabled={saving} className="px-5 py-3 bg-purple-600 disabled:bg-slate-400 text-white rounded-xl font-bold flex gap-2"><Save className="w-4 h-4" />{saving ? 'Đang lưu...' : lecturerEvaluation ? 'Cập nhật đánh giá' : 'Lưu đánh giá'}</button></form>}</div>;
}
